name: Python application
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@vX
    - name: Set up Python 3.10
      uses: actions/setup-python@vX
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with Pytest
      run: |
        pytest
    - name: Lint with Pylint
      run: |
        pylint ./utils.py
    - name: Format with Black
      run: |
        black --check .
